# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - easeTruckBackend

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          cd backend
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Install zip (if missing)
        run: sudo apt-get install zip -y
        
      - name: Zip artifact for deployment
        run: |
          cd backend
          zip -r ../release.zip .   # Zip contents and move to root folder
        
      - name: Check if release.zip exists
        run: |
          ls -l
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip  # Upload from root folder
        
        

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Unzip artifact
        run: |
            unzip release.zip -d ./backend  # Unzip into the backend folder or any directory where you want

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7BE61972441D43158E8482A9E18BA027 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C34F59FA4CE3441CAE6FDE55682A4739 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D5151B6281604CDF842902762A1A7732 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'easeTruckBackend'
          slot-name: 'Production'
          package: ./backend
          